//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class tbl_Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Urunler()
        {
            this.tbl_Satis = new HashSet<tbl_Satis>();
        }
    
        public int UrunID { get; set; }

        [Required(ErrorMessage = "Bu Alaný Boþ Býrakamazsýnýz!")]
        public string UrunAd { get; set; }

        [Required(ErrorMessage = "Bu Alaný Boþ Býrakamazsýnýz!")]
        public string Marka { get; set; }
        public Nullable<short> UrunKategori { get; set; }

        [Required(ErrorMessage = "Bu Alaný Boþ Býrakamazsýnýz!")]
        public Nullable<decimal> Fiyat { get; set; }

        [Required(ErrorMessage = "Bu Alaný Boþ Býrakamazsýnýz!")]
        public Nullable<byte> Stok { get; set; }
    
        public virtual tbl_Kategoriler tbl_Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Satis> tbl_Satis { get; set; }
    }
}
