//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Musteriler()
        {
            this.tbl_Satis = new HashSet<tbl_Satis>();
        }
    
        public int MusteriID { get; set; }

        [Required(ErrorMessage ="Bu Alaný Boþ Býrakamazsýnýz!")]
        [StringLength(50,ErrorMessage ="En Fazla 50 Karakterli Deðer Giriniz!")]
        public string MusteriAd { get; set; }
        
        [Required(ErrorMessage = "Bu Alaný Boþ Býrakamazsýnýz!")]
        [StringLength(50, ErrorMessage = "En Fazla 50 Karakterli Deðer Giriniz!")]
        public string MusteriSoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Satis> tbl_Satis { get; set; }
    }
}
